<?php

return [
    'defaultInfo' => [
        'score' => [
            [
                'Subject' => 'YetAnotherSubject',
                'Score' => 100
            ],
        ],
        'class' => [
            [
                'SampleClass1',
                '',
                '',
                '',
                '',
                '',
                ''
            ],
            [
                '',
                'SampleClass1',
                '',
                '',
                '',
                '',
                ''
            ],
            [
                '',
                '',
                'SampleClass1',
                '',
                '',
                '',
                ''
            ],
            [
                '',
                '',
                '',
                'SampleClass1',
                '',
                '',
                ''
            ],
            [
                '',
                '',
                '',
                '',
                'SampleClass1',
                '',
                ''
            ],
            [
                '',
                '',
                '',
                '',
                '',
                'SampleClass1',
                ''
            ],
            [
                '',
                '',
                '',
                '',
                '',
                '',
                'SampleClass1'
            ],
            [
                '',
                '',
                '',
                '',
                '',
                'SampleClass1',
                ''
            ],
            [
                '',
                '',
                '',
                '',
                'SampleClass1',
                '',
                ''
            ],
            [
                '',
                '',
                '',
                'SampleClass1',
                '',
                '',
                ''
            ],
            [
                '',
                '',
                'SampleClass1',
                '',
                '',
                '',
                ''
            ],
            [
                '',
                'SampleClass1',
                '',
                '',
                '',
                '',
                ''
            ],
            [
                'SampleClass1',
                '',
                '',
                '',
                '',
                '',
                ''
            ],
        ],
        'img' => [],
        'url' => [],
        'file' => [],
    ],
];
